apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spider-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: arizwana/spider-link-frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
